#!/bin/bash
packageLogFile="/var/log/SolarEdgeHeartbeat/current"

# Source SetupHelper resources
source "/data/SetupHelper/HelperResources/IncludeHelpers"

packageAction() {
    case $1 in
        INSTALL)
            logMessage "Installing SolarEdge Heartbeat Service..."
            installService $packageName

            logMessage "Patching QML UI..."
            cp "$scriptDir/qml/PageSolarEdge.qml" "$qmlDir/"
            
            # Remove any previous failed attempts to prevent corruption
            sed -i '/SolarEdge Heartbeat/d' "$qmlDir/PageSettings.qml"
            
            # Standard injection point used by SetupHelper
            sed -i '/model: VisibleItemModel {/a \ \ \ \ \ \ \ \ MbSubMenu { description: qsTr("SolarEdge Heartbeat"); subpage: Component { PageSolarEdge {} } }' "$qmlDir/PageSettings.qml"
            
            restartGui=true
            ;;
            
        UNINSTALL)
            logMessage "Uninstalling SolarEdge Heartbeat..."
            removeService $packageName
            sed -i '/SolarEdge Heartbeat/d' "$qmlDir/PageSettings.qml"
            rm -f "$qmlDir/PageSolarEdge.qml"

            # Remove any persisted package data (SetupHelper uses these locations)
            rm -rf "/data/$packageName"
            rm -rf "/data/setupOptions/$packageName"

            # Remove our own log files (if we created them)
            rm -rf "$(dirname "$packageLogFile")"
            
            restartGui=true
            ;;
    esac
}

if [ $scriptAction == 'NONE' ] ; then
    standardActionPrompt
else
    packageAction $scriptAction
fi

endScript
