#!/bin/bash
packageLogFile="/var/log/SolarEdgeHeartbeat/current"

# Source SetupHelper resources
source "/data/SetupHelper/HelperResources/IncludeHelpers"

packageAction() {
    case $1 in
        install|INSTALL)
            logMessage "Installing SolarEdge Heartbeat Service..."
            installService $packageName

            logMessage "Patching QML UI..."
            cp "$scriptDir/qml/PageSolarEdge.qml" "$qmlDir/"
            
            # Remove any previous failed attempts using our unique tag
            sed -i '/#SolarEdgeHeartbeat/d' "$qmlDir/PageSettings.qml"
            
            # Inject our menu item and hide a unique tag (#SolarEdgeHeartbeat) at the end of the line
            sed -i '/model: VisibleItemModel {/a \ \ \ \ \ \ \ \ MbSubMenu { description: qsTr("SolarEdge Heartbeat"); subpage: Component { PageSolarEdge {} } } #SolarEdgeHeartbeat' "$qmlDir/PageSettings.qml"
            
            restartGui=true
            ;;
            
        uninstall|UNINSTALL)
            logMessage "Uninstalling SolarEdge Heartbeat..."
            removeService $packageName
            
            # ONLY remove the line that contains our unique tag
            sed -i '/#SolarEdgeHeartbeat/d' "$qmlDir/PageSettings.qml"
            rm -f "$qmlDir/PageSolarEdge.qml"
            
            # Note: Do NOT delete /data/$packageName or /data/setupOptions. 
            # Package Manager handles deleting the package via the "Remove" button in the GUI.

            # We can, however, safely delete our own custom log folder
            rm -rf "$(dirname "$packageLogFile")"
            
            restartGui=true
            ;;
    esac
}

if [ $scriptAction == 'NONE' ] ; then
    standardActionPrompt
else
    packageAction $scriptAction
fi

endScript
