#!/bin/bash
packageLogFile="/var/log/SolarEdgeHeartbeat/current"

# Source the SetupHelper resources
source "/data/SetupHelper/HelperResources/IncludeHelpers"

packageAction() {
    case $1 in
        INSTALL)
            logMessage "Installing SolarEdge Heartbeat Service..."
            installService $packageName

            logMessage "Patching QML UI..."
            # Copy our custom page to the system directory
            cp "$scriptDir/qml/PageSolarEdge.qml" "$qmlDir/"
            
            # Remove any previous failed attempts
            sed -i '/SolarEdge Heartbeat/d' "$qmlDir/PageSettings.qml"
            
            # Inject the menu item at a known-good anchor point
            sed -i '/model: VisibleItemModel {/a \ \ \ \ \ \ \ \ MbSubMenu { description: qsTr("SolarEdge Heartbeat"); subpage: Component { PageSolarEdge {} } }' "$qmlDir/PageSettings.qml"
            
            restartGui=true
            ;;
            
        UNINSTALL)
            logMessage "Uninstalling SolarEdge Heartbeat..."
            removeService $packageName
            
            # Clean up PageSettings and remove the page
            sed -i '/SolarEdge Heartbeat/d' "$qmlDir/PageSettings.qml"
            rm -f "$qmlDir/PageSolarEdge.qml"
            
            restartGui=true
            ;;
    esac
}

# Standard SetupHelper execution block
if [ $scriptAction == 'NONE' ] ; then
    standardActionPrompt
else
    packageAction $scriptAction
fi

endScript
